### ISSUE TITLE
AutoScroll2目前速度有上限

### ISSUE THREAD

**Issue by leadra** [EilenC/Tampermonkey-Scripts#1]
chrome安裝
Chrome 目前是最新版本
版本 122.0.6261.112 (正式版本) (64 位元)
Cent Browser
版本 5.0.1002.354 (正式版本) (32 位元) (Chromium 102.0.5005.167)
目前不管提高到多少，大概都和0.77一樣，請問還能提高速度嗎?
不好意思，久久又來打擾了

**Comment by EilenC** [comment]
我也发现了, 在研究看看怎么处理

**Comment by EilenC** [comment]
> chrome安装 美分浏览器 目前不管提高到多少，大概都和0.77一样，请问还能提高速度吗？  不好意思，久久又来打扰了
> 
> chrome安裝 chrome安装 Chrome 目前是最新版本 版本 122.0.6261.112 (正式版本) (64 位元) Cent Browser 美分浏览器 版本 5.0.1002.354 (正式版本) (32 位元) (Chromium 102.0.5005.167) 目前不管提高到多少，大概都和0.77一樣，請問還能提高速度嗎? 目前不管提高到多少，大概都和0.77一样，请问还能提高速度吗？ 不好意思，久久又來打擾了  不好意思，久久又来打扰了

估计是 chromium 对dom的scroll 又做了什么修改  这感觉是个大问题,估计需要很长时间排查了

**Comment by leadra** [comment]
辛苦了，通用的都比較困難，就讓他放水流~"~

**Comment by EilenC** [comment]
> 辛苦了，通用的都比較困難，就讓他放水流~"~

问题已经fix了, 在 `greasyfork` 更新 `1.0.2` 版本

这次兼容了 Chrome与Edge(chromium)以及Firefox

**Comment by leadra** [comment]
回復晚了不好意思~感謝作者~!!
